### ISSUE TITLE
Roadmap page

### ISSUE THREAD

**Issue by hollisticated-horse** [syphon-org/landing#14]
A high level roadmap to help users or potential users track what is up and running, what is being worked on and what is planned for the future. 

Could use github in some way to indicate clearly on both the website and github what's going on.

**Comment by hollisticated-horse** [comment]
Okay, I'm going to see there is a way to use the github api to get the projects content for each release. See how that looks.

**Comment by hollisticated-horse** [comment]
Todo:

- [ ] setup page architecture within website
- [ ] check it works
- [ ] check out github api
- [ ] get page to generate styled elements from api

**Comment by octoshrimpy** [comment]
Looks like it wouldn't be too hard to do, as per [the official api](https://docs.github.com/en/rest/issues/issues#get-an-issue)

I was able to get the state of a closed issue, as well as its state reason. 
```sh
curl   -H "Accept: application/vnd.github+json"   https://api.github.com/repos/syphon-org/landing/issues/17 | grep "state"
```
![image](https://user-images.githubusercontent.com/7097172/197318394-9d91dbee-a416-43f2-b1cc-22875f504f0d.png)

attaching a bit of JS to the roadmap page, and having the issue number the specific checkmark is attached to just in a `data-gh-issue` attribute, it could make a request per attribute on page, and toggle the checkbox appropriately. at the end of each milestone, manually set them to checked to keep requests at minimum.


... In fact, I might be able to poke at this and get a PR going.

**Comment by hollisticated-horse** [comment]
Closing due to not using the software any more, and inactivity here.
